// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvrhtpbdcjnkejbifgze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cmh0cGJkY2pua2VqYmlmZ3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjc5NjMsImV4cCI6MjA3MjkwMzk2M30.9TdbhU-ZPVNg1bfBXWslhaod0JGdPu5NU3J3feJZgJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});